export const employees = [
  {
    id: 1,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "active",
    country: "Bangladesh",
  },
  {
    id: 2,
    name: "Jane Smith",
    role: "Designer",
    email: "sample@gmail.com",
    status: "Inactive",
    country: "England",
  },
  {
    id: 3,
    name: "Sam Green",
    role: "Manager",
    email: "sample@gmail.com",
    status: "active",
    country: "China",
  },
  {
    id: 4,
    name: "Sam Green",
    role: "Manager",
    email: "sample@gmail.com",
    status: "Inactive",
    country: "Russia",
  },
  {
    id: 5,
    name: "Sam Green",
    role: "Manager",
    email: "sample@gmail.com",
    status: "active",
    country: "Turkey",
  },
  {
    id: 6,
    name: "Sam Green",
    role: "Manager",
    email: "sample@gmail.com",
    status: "Inactive",
    country: "Poland",
  },
  {
    id: 7,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "active",
    country: "USA",
  },
  {
    id: 8,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "active",
    country: "Canada",
  },
  {
    id: 9,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "active",
  },
  {
    id: 10,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "active",
  },
  {
    id: 11,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "active",
  },
  {
    id: 12,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "active",
  },
  {
    id: 13,
    name: "Jane Smith",
    role: "Designer",
    email: "sample@gmail.com",
    status: "Inactive",
    country: "England",
  },
  {
    id: 14,
    name: "Sam Green",
    role: "Manager",
    email: "sample@gmail.com",
    status: "active",
    country: "England",
  },
  {
    id: 15,
    name: "Sam Green",
    role: "Manager",
    email: "sample@gmail.com",
    status: "active",
  },
  {
    id: 16,
    name: "Sam Green",
    role: "Manager",
    email: "sample@gmail.com",
    status: "Inactive",
    country: "England",
  },
  {
    id: 17,
    name: "Sam Green",
    role: "Manager",
    email: "sample@gmail.com",
    status: "active",
  },
  {
    id: 18,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "Inactive",
    country: "England",
  },
  {
    id: 19,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "active",
    country: "England",
  },
  {
    id: 20,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "active",
  },
  {
    id: 21,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "active",
  },
  {
    id: 22,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "active",
    country: "England",
  },
  {
    id: 23,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "active",
  },
  {
    id: 24,
    name: "Jane Smith",
    role: "Designer",
    email: "sample@gmail.com",
    status: "Inactive",
  },
  {
    id: 25,
    name: "Sam Green",
    role: "Manager",
    email: "sample@gmail.com",
    status: "active",
  },
  {
    id: 26,
    name: "Sam Green",
    role: "Manager",
    email: "sample@gmail.com",
    status: "active",
  },
  {
    id: 27,
    name: "Sam Green",
    role: "Manager",
    email: "sample@gmail.com",
    status: "active",
  },
  {
    id: 28,
    name: "Sam Green",
    role: "Manager",
    email: "sample@gmail.com",
    status: "active",
  },
  {
    id: 29,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "active",
    country: "England",
  },
  {
    id: 30,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "active",
  },
  {
    id: 31,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "active",
  },
  {
    id: 32,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "active",
  },
  {
    id: 33,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "active",
  },
  {
    id: 34,
    name: "John Doe",
    role: "Developer",
    email: "sample@gmail.com",
    status: "active",
  },
];
