export const categories = [
  {
    id: 1,
    categoryName: "Electronics",
    stockStatus: "In Stock",
    categoryType: "Physical",
    stockType: "Available",
    quantity: 100,
  },
  {
    id: 2,
    categoryName: "Mobile Phones",
    stockStatus: "In Stock",
    categoryType: "Physical",
    stockType: "Available",
    quantity: 50,
  },
  {
    id: 3,
    categoryName: "Laptops & Computers",
    stockStatus: "Out of Stock",
    categoryType: "Physical",
    stockType: "Not Available",
    quantity: 0,
  },
  {
    id: 4,
    categoryName: "Headphones",
    stockStatus: "In Stock",
    categoryType: "Physical",
    stockType: "Available",
    quantity: 200,
  },
  {
    id: 5,
    categoryName: "Smart Watches",
    stockStatus: "Low Stock",
    categoryType: "Physical",
    stockType: "Limited",
    quantity: 20,
  },
  {
    id: 6,
    categoryName: "Home Appliances",
    stockStatus: "In Stock",
    categoryType: "Physical",
    stockType: "Available",
    quantity: 150,
  },
  {
    id: 7,
    categoryName: "Books",
    stockStatus: "In Stock",
    categoryType: "Digital",
    stockType: "Available",
    quantity: 1000,
  },
  {
    id: 8,
    categoryName: "E-books",
    stockStatus: "In Stock",
    categoryType: "Digital",
    stockType: "Available",
    quantity: 500,
  },
  {
    id: 9,
    categoryName: "Online Courses",
    stockStatus: "In Stock",
    categoryType: "Digital",
    stockType: "Available",
    quantity: 200,
  },
  {
    id: 10,
    categoryName: "Subscription Services",
    stockStatus: "In Stock",
    categoryType: "Service",
    stockType: "Available",
    quantity: 300,
  },
  {
    id: 11,
    categoryName: "Fitness Equipment",
    stockStatus: "In Stock",
    categoryType: "Physical",
    stockType: "Available",
    quantity: 80,
  },
  {
    id: 12,
    categoryName: "Furniture",
    stockStatus: "Out of Stock",
    categoryType: "Physical",
    stockType: "Not Available",
    quantity: 0,
  },
  {
    id: 13,
    categoryName: "Toys",
    stockStatus: "In Stock",
    categoryType: "Physical",
    stockType: "Available",
    quantity: 120,
  },
  {
    id: 14,
    categoryName: "Beauty Products",
    stockStatus: "Low Stock",
    categoryType: "Physical",
    stockType: "Limited",
    quantity: 30,
  },
  {
    id: 15,
    categoryName: "Services",
    stockStatus: "In Stock",
    categoryType: "Service",
    stockType: "Available",
    quantity: 50,
  },
];
