export const products = [
  {
    id: 1,
    productName: "iPhone 15 Pro Max",
    color: "Black Titanium",
    category: "Smartphone",
    available: "true",
    quantity: "50",
    price: "1399",
    brand: "Apple",
  },
  {
    id: 2,
    productName: "Samsung Galaxy S25 Ultra",
    color: "Phantom Black",
    category: "Smartphone",
    available: "true",
    quantity: "30",
    price: "1299",
    brand: "Samsung",
  },
  {
    id: 3,
    productName: "OnePlus 12",
    color: "Eternal Green",
    category: "Smartphone",
    available: "true",
    quantity: "75",
    price: "899",
    brand: "OnePlus",
  },
  {
    id: 4,
    productName: "Google Pixel 8 Pro",
    color: "Obsidian",
    category: "Smartphone",
    available: "false",
    quantity: "0",
    price: "1099",
    brand: "Google",
  },
  {
    id: 5,
    productName: "Xiaomi Redmi Note 13 Pro",
    color: "Polar White",
    category: "Smartphone",
    available: "true",
    quantity: "100",
    price: "399",
    brand: "Xiaomi",
  },
  {
    id: 6,
    productName: "Realme 14 Pro+",
    color: "Sunburst Gold",
    category: "Smartphone",
    available: "true",
    quantity: "120",
    price: "499",
    brand: "Realme",
  },
  {
    id: 7,
    productName: "Asus ROG Phone 8",
    color: "Matte Black",
    category: "Gaming Phone",
    available: "false",
    quantity: "0",
    price: "1299",
    brand: "Asus",
  },
  {
    id: 8,
    productName: "Oppo Reno 13",
    color: "Sky Blue",
    category: "Smartphone",
    available: "true",
    quantity: "85",
    price: "599",
    brand: "Oppo",
  },
  {
    id: 9,
    productName: "Vivo V30 Pro",
    color: "Pearl White",
    category: "Smartphone",
    available: "true",
    quantity: "60",
    price: "649",
    brand: "Vivo",
  },
  {
    id: 10,
    productName: "Sony Xperia 1 VI",
    color: "Frosted Gray",
    category: "Smartphone",
    available: "false",
    quantity: "0",
    price: "1199",
    brand: "Sony",
  },
  {
    id: 11,
    productName: "Nothing Phone 2",
    color: "Transparent Black",
    category: "Smartphone",
    available: "true",
    quantity: "45",
    price: "799",
    brand: "Nothing",
  },
  {
    id: 12,
    productName: "Motorola Edge 40 Pro",
    color: "Nebula Blue",
    category: "Smartphone",
    available: "true",
    quantity: "55",
    price: "749",
    brand: "Motorola",
  },
];
