export const brands = [
  {
    id: 1,
    brandName: "Apple",
    brandStatus: "Active",
    phone: "01700692775",
    email: "support@apple.com",
    websiteURL: "https://www.apple.com",
  },
  {
    id: 2,
    brandName: "Nike",
    brandStatus: "inActive",
    phone: "01700344645",
    email: "support@nike.com",
    websiteURL: "https://www.nike.com",
  },
  {
    id: 3,
    brandName: "Samsung",
    brandStatus: "Active",
    phone: "01700205300",
    email: "support@samsung.com",
    websiteURL: "https://www.samsung.com",
  },
  {
    id: 4,
    brandName: "Microsoft",
    brandStatus: "inActive",
    phone: "01700642767",
    email: "support@microsoft.com",
    websiteURL: "https://www.microsoft.com",
  },
  {
    id: 5,
    brandName: "Adidas",
    brandStatus: "inActive",
    phone: "01700913284",
    email: "support@adidas.com",
    websiteURL: "https://www.adidas.com",
  },
  {
    id: 6,
    brandName: "Tesla",
    brandStatus: "Active",
    phone: "01700518375",
    email: "support@tesla.com",
    websiteURL: "https://www.tesla.com",
  },
  {
    id: 7,
    brandName: "Google",
    brandStatus: "Active",
    phone: "01700253000",
    email: "support@google.com",
    websiteURL: "https://www.google.com",
  },
  {
    id: 8,
    brandName: "Sony",
    brandStatus: "Active",
    phone: "01700674821",
    email: "support@sony.com",
    websiteURL: "https://www.sony.com",
  },
  {
    id: 9,
    brandName: "Amazon",
    brandStatus: "Active",
    phone: "01700280433",
    email: "support@amazon.com",
    websiteURL: "https://www.amazon.com",
  },
  {
    id: 10,
    brandName: "Coca-Cola",
    brandStatus: "Active",
    phone: "01700438265",
    email: "support@coca-cola.com",
    websiteURL: "https://www.coca-cola.com",
  },
  {
    id: 11,
    brandName: "Pepsi",
    brandStatus: "Active",
    phone: "01700433265",
    email: "support@pepsi.com",
    websiteURL: "https://www.pepsi.com",
  },
  {
    id: 12,
    brandName: "BMW",
    brandStatus: "Active",
    phone: "01700382000",
    email: "support@bmw.com",
    websiteURL: "https://www.bmw.com",
  },
  {
    id: 13,
    brandName: "Mercedes-Benz",
    brandStatus: "Active",
    phone: "01700711170",
    email: "support@mercedes.com",
    websiteURL: "https://www.mercedes-benz.com",
  },
  {
    id: 14,
    brandName: "Intel",
    brandStatus: "Active",
    phone: "01700765808",
    email: "support@intel.com",
    websiteURL: "https://www.intel.com",
  },
  {
    id: 15,
    brandName: "HP",
    brandStatus: "Active",
    phone: "01700474683",
    email: "support@hp.com",
    websiteURL: "https://www.hp.com",
  },
];
